### ISSUE TITLE
movej timeout

### ISSUE THREAD

**Issue by neale** [vimalabs/VIMABench#10]
Hi there, thanks for your very interesting work. 
I'm trying to run the simulator in a simple gym-style setup and I'm getting a weird warning every episode:

`Warning: movej exceeded 5 second timeout. Skipping.`

I'm wondering if this is because of a bad predicted action, or some deeper problem

EDIT: I forgot to mention that episodes are finishing after 1 or 2 steps. Even a 20 second timeout is violated

It seems that randomly sampling from the action space results in poses that the simulator cannot complete. Considering that many methods rely on initial random exploration, I'm not sure what to do here.

**Comment by yunfanjiang** [comment]
Hi @neale, thanks for your interest in our work.

> I'm wondering if this is because of a bad predicted action, or some deeper problem

You are right. This is because of bad joint poses that cannot be reached within 5s as seen [here](https://github.com/vimalabs/VIMABench/blob/224c2d870d6063d90215201ba42d4211ddc957d7/vima_bench/env/base.py#L692).

> It seems that randomly sampling from the action space results in poses that the simulator cannot complete. Considering that many methods rely on initial random exploration, I'm not sure what to do here.

True. Random exploration on robots (even in simulation) is dangerous. Since we provide [oracles](https://github.com/vimalabs/VIMABench/tree/main#oracle) that can generate expert demonstrations, I'd recommend to leverage them to bootstrap the policy.
