### ISSUE TITLE
Depth image

### ISSUE THREAD

**Issue by XihangYU630** [vimalabs/VIMABench#5]
It says that _assert "depth" not in modalities, "FIXME: fix depth normalization"_. Can we change the modality to include "depth"?

**Comment by XihangYU630** [comment]
After adding depth in modality and comment out _"depth" not in modalities, "FIXME: fix depth normalization"_, there is another error saying _assert self.observation_space.contains(obs)_

**Comment by yunfanjiang** [comment]
Thanks for playing with our codebase!
Please note that our models do not require depth modality during training, therefore the codebase may not support it out of the box. IIRC, the issue is about the modified camera setting such that returned depth values are within a weird range. It may require some modifications to fix. Contributions from the community is welcomed!
