### ISSUE TITLE
Question about getCameraImage function

### ISSUE THREAD

**Issue by XihangYU630** [vimalabs/VIMABench#7]
Why in the function p.getCameraImage, it sets flags=p.ER_SEGMENTATION_MASK_OBJECT_AND_LINKINDEX,
renderer=p.ER_BULLET_HARDWARE_OPENGL?

 _, _, color, depth, segm = p.getCameraImage(
            width=image_size[1],
            height=image_size[0],
            viewMatrix=viewm,
            projectionMatrix=projm,
            flags=p.ER_SEGMENTATION_MASK_OBJECT_AND_LINKINDEX,
            renderer=p.ER_BULLET_HARDWARE_OPENGL,
            physicsClientId=self.client_id,
        )

**Comment by yunfanjiang** [comment]
Thanks for the question. We set `ER_SEGMENTATION_MASK_OBJECT_AND_LINKINDEX` because we also want to provide ground-truth object segmentation. For `ER_BULLET_HARDWARE_OPENGL` because we use headless rendering. We'd recommend [PyBullet doc](https://docs.google.com/document/d/10sXEhzFRSnvFcl3XxNGhnD4N2SedqwdAvK3dsihxVUA/edit?usp=sharing) for more details.
