### ISSUE TITLE
Any example for training an RL agent online or offline?

### ISSUE THREAD

**Issue by GilgameshD** [vimalabs/VIMABench#8]
Thanks for providing such an excellent benchmark environment! 

I wonder if it is possible to provide examples of using offline datasets or online environments to train some standard RL agents. It will be very helpful to make users quickly conduct experiments in this benchmark. I know that you provide another repo for the methods you use in the paper, but the training part seems not included.

Thanks!

**Comment by yunfanjiang** [comment]
Hi, thank you for your interest in our work. Since the training code is deeply coupled with company infrastructure and internal codebases, we currently don't have any ETA of releasing them. We will let you know if anything changes.

That being said, because VIMABench follows the Gym API, it still can be easily incorporated into your favorite RL libraries. The only caveat is the running speed. Since each environment step in VIMABench consists of several simulation steps, the low throughput may become a concern if you want to train RL agents in an online manner.

Let me know if you have further questions.
