### ISSUE TITLE
Questions about scene layout and rendering

### ISSUE THREAD

**Issue by Aryan9101** [vimalabs/VIMABench#9]
1. When I run a task, the default scene appears to have a yellow background and a gray workstation. Is it possible to change the urdf files to get the same visuals shown in this repository's README?
2. Is it possible to get each image frame (that goes into making the video demo) and action (taken internally by the sim) from an oracle-executed path?

Thank you so much! I've been loving Vima so far!

**Comment by yunfanjiang** [comment]
Hey there, thank you for your interest in our project! Regarding your questions

1. Yes. But please note that we use [NVISII](https://github.com/owl-project/NVISII) to enhance the visual appearance in README for better demonstration. The data generation and training are still performed on the original rendering.

2. Yes. Regarding per-frame image, if you just want to record videos, you can simply pass `record_gui = True` to `vima_bench.make()`. However, if you want per-frame images for other purposes such as training, please note that it will significantly slow down the simulation because we need to render RGB images every frame. See [here](https://github.com/cliport/cliport/blob/47bf8298f6b664365ab042eb7ac0bcaf5df60254/cliport/environments/environment.py#L235-L240) for example code.

Regarding per-frame action, because we use action primitives (pick-place and sweep), see [here](https://github.com/vimalabs/VIMABench/blob/8b0de7923c14107043a13a0a6068a9012433dafa/vima_bench/tasks/components/action_primitives.py#L177) for how pick-place works under the hood, [here](https://github.com/vimalabs/VIMABench/blob/8b0de7923c14107043a13a0a6068a9012433dafa/vima_bench/tasks/components/action_primitives.py#L244) for how sweep works. In general, both primitives call an [internal function](https://github.com/vimalabs/VIMABench/blob/8b0de7923c14107043a13a0a6068a9012433dafa/vima_bench/env/base.py#L692-L722) to move robot joints.

Let me know if you have further questions!
